spring:
  datasource:
    # 数据库用户名
    name: root
    # 数据库密码
    password: fanjianglong
    # 数据库地址
    url: jdbd:mysql://127.0.0.1:3306/owerwatch_league
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池使用Druid
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化连接数
    initial-size: 3
    # 最小连接数
    minIdle: 5
    # 最大连接数
    maxActive: 5
    # 连接等待超时时间
    maxWait: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
